<h3>Data Merging - Using Python</h3>
<hr>
<br>
Here, we have several .csv files scattered across various different directories in distinct hierarchies.
Thus, we used Python to merge them into a single -> .csv file

This is acheieved by
- Declare paths in a list
- Use Pandas and Scipy -> V stack to merge them into a singular dataframe
- Export the dataframe into a .csv file.

<hr><h4><b>Breakdown File - Merging

In [ ]:
#Declaration of paths for the files to be read

paths = ["/Users/samarth/Documents/SIH 26/final_syb/Breakdown_ALL.csv",
         "/Users/samarth/Documents/SIH 26/final_syb/Breakdown.csv"]

In [16]:
#Importing the required libraries

import pandas as pd
import numpy as np
from scipy.sparse import vstack

data = []

for path in paths:
    temp = pd.read_csv(path)
    data.append(temp.iloc[:, :2].values)

merged = np.vstack(data)

df_breakdown = pd.DataFrame(
    merged,
    columns=pd.read_csv(paths[0]).columns[:2]
)
df_breakdown.columns = ["Collector_Emitter_Voltage_Vce", "Leakage_Current_Ic"]

df_breakdown

      Collector_Emitter_Voltage_Vce  Leakage_Current_Ic
0                          2.020181        5.885971e-09
1                          2.040083        5.927931e-09
2                          2.060686        5.913162e-09
3                          2.080598        5.896354e-09
4                          2.100827        6.043535e-09
...                             ...                 ...
3785                       4.952857        2.500220e-04
3786                       4.952870        2.500230e-04
3787                       4.952888        2.500230e-04
3788                       4.952896        2.500230e-04
3789                       4.952880        2.500230e-04

[3790 rows x 2 columns]

In [17]:
#Exporting the merged dataframe to a new CSV file

df_breakdown.to_csv("/Users/samarth/Documents/SIH 26/final_syb/dataset/Breakdown.csv", index=False)

<hr><h4><b>Leakage IV - Merging

In [9]:
paths = ["/Users/samarth/Documents/SIH 26/final_syb/LeakageIV_ALL.csv",
         "/Users/samarth/Documents/SIH 26/final_syb/LeakageIV.csv"]

In [10]:
data = []

for path in paths:
    temp = pd.read_csv(path)
    data.append(temp.iloc[:, :2].values)

merged = np.vstack(data)

df_leakage = pd.DataFrame(
    merged,
    columns=pd.read_csv(paths[0]).columns[:2]
)
df_leakage.columns = ["Applied_Voltage", "Leakage_Current"]

df_leakage

      Applied_Voltage  Leakage_Current
0            1.007554     3.850000e-09
1            4.011488     1.030000e-08
2            7.021188     1.870000e-08
3           10.063710     2.690000e-08
4           13.051750     3.490000e-08
...               ...              ...
3785       587.999300     4.300729e-06
3786       590.989900     4.340944e-06
3787       594.033800     4.382679e-06
3788       597.042800     4.424245e-06
3789       600.050900     4.466115e-06

[3790 rows x 2 columns]

In [12]:
df_leakage.to_csv("/Users/samarth/Documents/SIH 26/final_syb/dataset/LeakageIV.csv", index=False)

<hr><b><h4>Turn On Files - Merging

In [13]:
paths = ["/Users/samarth/Documents/SIH 26/final_syb/TurnOn.csv",
         "/Users/samarth/Documents/SIH 26/final_syb/TurnOn_ALL.csv"]

In [14]:
data = []

for path in paths:
    temp = pd.read_csv(path)
    data.append(temp.iloc[:, :2].values)

merged = np.vstack(data)

df_turn_on = pd.DataFrame(
    merged,
    columns=pd.read_csv(paths[0]).columns[:2]
)
df_turn_on.columns = ["Gate_Voltage", "Collector_Current"]

df_turn_on

      Gate_Voltage  Collector_Current
0         2.020181       5.885971e-09
1         2.040083       5.927931e-09
2         2.060686       5.913162e-09
3         2.080598       5.896354e-09
4         2.100827       6.043535e-09
...            ...                ...
3785      4.952857       2.500220e-04
3786      4.952870       2.500230e-04
3787      4.952888       2.500230e-04
3788      4.952896       2.500230e-04
3789      4.952880       2.500230e-04

[3790 rows x 2 columns]

In [15]:
df_turn_on.to_csv("/Users/samarth/Documents/SIH 26/final_syb/dataset/TurnOn.csv", index=False)